apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  namespace: demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: node-api

  template:
    metadata:
      labels:
        app: node-api

    spec:
      containers:
      - name: node-api
        image: bharathiacr123.azurecr.io/node-api:d484d6d45e7252793680c82c1e91ab578ea8035a

        ports:
        - containerPort: 5000