apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  namespace: demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: node-api

  template:
    metadata:
      labels:
        app: node-api

    spec:
      containers:
      - name: node-api
        image: bharathiacr123.azurecr.io/node-api:51d422001ecdb2f158f6d9c15d67b4a1656558c1

        ports:
        - containerPort: 5000