apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  namespace: demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: node-api

  template:
    metadata:
      labels:
        app: node-api

    spec:
      containers:
      - name: node-api
        image: bharathiacr123.azurecr.io/node-api:41e740ff588b597ab1a43c15558078734d7bedb1

        ports:
        - containerPort: 5000