apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: aks-demo-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: 'https://github.com/Bharathi28092000/aks-gitops.git'
    targetRevision: HEAD
    path: k8s

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo

  syncPolicy:
    automated:
      prune: false
      selfHeal: true