apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui
  namespace: demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: react-ui

  template:
    metadata:
      labels:
        app: react-ui

    spec:
      containers:
      - name: react-ui
        image: bharathiacr123.azurecr.io/react-ui:7a958c8a1f72346b8c15b2c6f9d90d9ac8e7a8c0

        ports:
        - containerPort: 80