apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui
  namespace: demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: react-ui

  template:
    metadata:
      labels:
        app: react-ui

    spec:
      containers:
      - name: react-ui
        image: bharathiacr123.azurecr.io/react-ui:51d422001ecdb2f158f6d9c15d67b4a1656558c1

        ports:
        - containerPort: 80