apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui
  namespace: demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: react-ui

  template:
    metadata:
      labels:
        app: react-ui

    spec:
      containers:
      - name: react-ui
        image: bharathiacr123.azurecr.io/react-ui:d484d6d45e7252793680c82c1e91ab578ea8035a

        ports:
        - containerPort: 80