name: AKS GitOps Pipeline

on:
  push:
    branches:
      - master

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
        password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

    - name: Build React UI
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/react-ui:${{ github.sha }} ./ui

    - name: Build Node API
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/node-api:${{ github.sha }} ./api

    - name: Push React UI
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/react-ui:${{ github.sha }}

    - name: Push Node API
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/node-api:${{ github.sha }}

    - name: Update UI Deployment YAML
      run: |
        sed -i "s|image:.*react-ui.*|image: ${{ secrets.ACR_LOGIN_SERVER }}/react-ui:${{ github.sha }}|g" k8s/ui-deployment.yaml

    - name: Update API Deployment YAML
      run: |
        sed -i "s|image:.*node-api.*|image: ${{ secrets.ACR_LOGIN_SERVER }}/node-api:${{ github.sha }}|g" k8s/api-deployment.yaml

    - name: Commit Updated YAML
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        git add .

        git commit -m "Update image tags" || echo "No changes to commit"

        git push origin master